version: "3"

services:
  namenode:
    image: somkiat/hadoop-namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=demo_01
    env_file:
      - ./hadoop.env

  datanode:
    image: somkiat/hadoop-datanode
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CLUSTER_NAME=demo_01
    env_file:
      - ./hadoop.env


volumes:
  hadoop_namenode:
  hadoop_datanode: