apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
data:
  CLUSTER_NAME: demo_01
  CORE_CONF_fs_defaultFS: hdfs://hdfs-namenode-0.hdfs-namenode:9000
  CORE_CONF_hadoop_http_staticuser_user: "root"
  CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
  CORE_CONF_hadoop_proxyuser_hue_groups: "*"
  CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec

  HDFS_CONF_dfs_webhdfs_enabled: "true"
  HDFS_CONF_dfs_permissions_enabled: "false"
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"

  HDFS-SITE.XML_dfs.namenode.name.dir: /data/namenode
  HDFS-SITE.XML_dfs.datanode.data.dir: /data/datanode
  LOG4J.PROPERTIES_log4j.rootLogger: INFO, stdout
  LOG4J.PROPERTIES_log4j.appender.stdout: org.apache.log4j.ConsoleAppender
  LOG4J.PROPERTIES_log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
  LOG4J.PROPERTIES_log4j.appender.stdout.layout.ConversionPattern: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
  CORE-SITE.XML_fs.defaultFS: hdfs://hdfs-namenode-0.hdfs-namenode:9820/
  HDFS-SITE.XML_dfs.namenode.rpc-address: hdfs-namenode-0.hdfs-namenode:9820