apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: hdfs-namenode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: hdfs
      component: namenode
  template:
    metadata:
      labels:
        app: hdfs
        component: namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: somkiat/hadoop-namenode
        envFrom:
        - configMapRef:
            name: hdfs-config
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}