apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  clusterIP: None
  ports:
  - port: 9870
    name: web
  - port: 9000
    name: internal
  selector:
    app: hdfs
    component: namenode